### ISSUE TITLE
How to improve performance?

### ISSUE THREAD

**Issue by And96** [fisherman-23/colorgram-dart#1]
Is it possible to get only the main color?

100ms is pretty slow for lists with hundreds of items

**Comment by fisherman-23** [comment]
yes, you can return only the main color by specifying it in the function parameter -> extractColor(image, 1);

however, this would not yield significant performance improvement
from my testing, the problem lies in the decoding portion of the program.

up to 70% of the time is spent decoding the images from bytes, this is likely due to the image library used. I will look into this further, let me know if you have any suggestions.

**Comment by And96** [comment]
> yes, you can return only the main color by specifying it in the function parameter -> extractColor(image, 1);
> 
> however, this would not yield significant performance improvement
> from my testing, the problem lies in the decoding portion of the program.
> 
> up to 70% of the time is spent decoding the images from bytes, this is likely due to the image library used. I will look into this further, let me know if you have any suggestions.

I already done images decoding in the past.

1 trick, to improve performance, for big images, is to resize the image (e.g. scale down to 30x30px) and then do color extraction on the resized image.

You'll see the same colors but 100 times faster. 😉

**Comment by fisherman-23** [comment]
Hi And96, the latest version 2.0.0 implemented your ImageProvider suggestions & other performance optimizations. As such, performance has been greatly improved and ease of use as well.

Benchmarks: (Desktop) without resizing

    512x512 JPEG in ~ 30ms
    5120x1440 JPEG in ~200ms

with resizing i was able to get it down to ~20ms and ~100ms respectively

Hope that this is more suited for you. Thanks again.
